---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "Andrea Virgen"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))

```

# Health Indicators in Texas Counties

## Andrea Virgen

### Introduction 

I'm interested to see how and if there are correlations between rates of obesity and sufficient physical activity in regards to life expectancy. I would infer that counties with the highest rates of obesity would have lower life expectancy, but it remains to be seen if higher rates of sufficient exercise compensates for these rates. The first dataset(phys) shows percentage prevalence of each location's population that achieves a sufficient amount of physical activity - specificity of measurement or sample size is unknown. The second dataset(obesity) shows percentage prevalence of obesity(criteria not given), normalized by age. The final dataset(life) houses life expectancies by county.

```{R}
library(readr)
library(tidyverse)
library(readxl)

phys <- read_excel("IHME_county_data_LifeExpectancy_Obesity_PhysicalActivity_TEXAS.xls", 
    sheet = "Physical Activity")

obesity <- read_excel("IHME_county_data_LifeExpectancy_Obesity_PhysicalActivity_TEXAS.xls", 
    sheet = "Obesity")

life <- read_excel("IHME_county_data_LifeExpectancy_Obesity_PhysicalActivity_TEXAS.xls", 
    sheet = "Life Expectancy")

```

### Tidying: Reshaping

Because these datasets have one numeric variable each, I am reshaping them to be combined on the basis of Location, Sex, and Year. The life expectancy(life) dataset was collected from years that do not overlap with the data from the other three datasets, so I will be taking the average from the data available for a later comparison with the other variables.

```{R}

life %>%
  select(-14:15) %>%
  pivot_longer(-1, names_to="desc", values_to="Life Expectancy") %>%
  rename("Location" = "State/County") %>%
  separate(desc, into = c("desc2", "Year"), sep=", ") %>%
  separate(desc2, into=c("Sex", NA)) %>%
  filter(Sex!="Difference") %>%
  group_by(Location, Sex) %>%
  transmute("Avg Life Expectancy"= sum(`Life Expectancy`)/n()) %>%
  distinct() -> life

phys %>%
  select(1:7)%>%
  pivot_longer(c(2:7), names_to = "desc", values_to= "Percent Active") %>%
  separate(desc, into=c("desc2", "year"), sep=", ") %>%
  separate(desc2, into =c("Sex",NA,NA,NA,NA)) %>%
  separate(year, into="Year") %>%
  rename(Location = "State/County") -> phys

obesity %>%
  select(1:7) %>%
  pivot_longer(c(2:7), names_to = "desc", values_to= "Percent Obese") %>%
  separate(desc, into =c("desc2", "Year"), sep=", ") %>%
  separate(desc2, into=c("Sex", NA, NA)) %>%
  separate(Year, into="Year") %>%
  rename(Location = "State/County") -> obesity

  
```

    
### Joining/Merging

```{R}
inner_join(phys, obesity, by=c("Location", "Sex", "Year")) %>%
  left_join(life, by=c("Location", "Sex")) -> health_indicators

  

```

Because phys and obesity are the same length, I can perform an inner join without losing any data. My life dataset is averages over a span of 25 years, so I will have repeated numbers for each Location after perfoming a left join to the previously inner-joined dataset.

###  Wrangling

```{R}

health_indicators %>%
  na.omit -> health_indicators

# highest life expectancy for males
health_indicators %>%
  arrange(desc(`Avg Life Expectancy`)) %>%
  select(1:2, 6) %>%
  group_by(Location, Sex) %>%
  filter(Sex=="Male") %>%
  distinct()

# highest life expectancy for females
health_indicators %>%
  arrange(desc(`Avg Life Expectancy`)) %>%
  select(1:2, 6) %>%
  group_by(Location, Sex) %>%
  filter(Sex=="Female") %>%
  distinct()
  
# average obesity rates by year
health_indicators %>%
  filter(Location!=c("United States", "Texas")) %>%
  group_by(Year, Sex) %>%
  summarize(`Overall Average Percent of Population Considered Obese` = sum(`Percent Obese`)/n(), `Overall Average Percent of Population Considered Sufficiently Active` = sum(`Percent Active`)/n())

# highest performers above the mean
health_indicators %>%
  group_by(Location) %>%
  filter(`Percent Active` > mean(`Percent Active`)) %>%
  arrange(desc(`Percent Active`))

# how often does active percent exceed obese percent?
health_indicators %>%
  mutate(`Higher Percent` = ifelse(`Percent Active` > `Percent Obese`, "Active", "Obese")) -> comparison

comparison %>%
  filter(`Higher Percent` == "Obese") %>%
  arrange(desc(`Percent Obese`)) %>%
  str_match_all("20[0-9]{2}") %>%
  unlist() %>%
  table()


```



### Visualizing

```{R}
health_indicators %>%
  ggplot(aes(`Avg Life Expectancy`, `Percent Active`, color=Sex)) + geom_point() + scale_color_brewer(palette="Set1") + geom_smooth() + xlab("Average Life Expectancy (1985 - 2010)") + ylab("Percent Active (2001, 2009, 2011)")
```
Here I am examining the correlation between percent of population that is sufficiently active and life expectancy averaged from data points taken in 5 year intervals from 1985 - 2010. A few interesting takeaways: although there is a noticeable correlation between size of active sub-population and the overall life expectancy of males in each county, females greatly exceed male life expectancy with minimal overlap; even though larger sub-populations of males get more physical activity overall, women still have much higher life expectancy across each county; there is also an odd drop off in size of sub-population that gets sufficient physical activity and the average life expectancy in a few counties.


```{R}
comparison %>%
  ggplot(aes(`Higher Percent`, fill = `Higher Percent`)) + geom_bar() + theme_dark() + ylab("Number of Counties") + xlab("Larger Percent of Population") + facet_grid(~Year) 
```

Year-to-year, most Texas counties have larger populations of sufficiently active individuals, that is, the percentage of sufficiently active individuals exceeds that of the percentage of obese individuals. As time has progressed, there has been a slight decrease in the amount of counties with larger percentage of sufficiently active individuals in comparison to percentage of obese individuals. This finding is consistent for both males and females.

```{R}
health_indicators %>%
  ggplot(aes(`Percent Obese`, fill = Year)) + geom_density() + xlab("Percent of Population Considered Obese") + facet_grid(~Sex)
```
Each distribution of obesity percentage per county has shifted while maintaining a normal distribution and steady increase over time. Males tend to have more counties with larger obese populations, but females tend to have larger obese populations per county.


### Concluding Remarks

I expected there to be progressively higher rates of obesity, but I didn't foresee such high rates of individuals getting sufficient physical activity year-over-year. It would be worth doing follow-up research to see if there were confounding factors to these findings: _- Were physical activity rates self-reported?_
                           _- Were the same groups measured each year?_
                           _-Were the sample sizes used unbiased representations of the populations of interest?_





